apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: {{ .Values.redisCart.replicaCount }}
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.redisCart.image.repository }}:{{ .Values.redisCart.image.tag }}"
        ports:
        - containerPort: {{ .Values.redisCart.port }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.redisCart.port }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.redisCart.port }}
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          requests:
            cpu: {{ .Values.redisCart.resources.requests.cpu }}
            memory: {{ .Values.redisCart.resources.requests.memory }}
          limits:
            cpu: {{ .Values.redisCart.resources.limits.cpu }}
            memory: {{ .Values.redisCart.resources.limits.memory }}
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: {{ .Values.redisCart.port }}
    targetPort: {{ .Values.redisCart.port }}
