apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: {{ .Values.shippingservice.replicaCount }}
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: shippingservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.shippingservice.image.repository }}:{{ .Values.shippingservice.image.tag }}"
        ports:
        - containerPort: {{ .Values.shippingservice.port }}
        env:
        - name: PORT
          value: "{{ .Values.shippingservice.port }}"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.shippingservice.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.shippingservice.port }}
        resources:
          requests:
            cpu: {{ .Values.shippingservice.resources.requests.cpu }}
            memory: {{ .Values.shippingservice.resources.requests.memory }}
          limits:
            cpu: {{ .Values.shippingservice.resources.limits.cpu }}
            memory: {{ .Values.shippingservice.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: {{ .Values.shippingservice.port }}
    targetPort: {{ .Values.shippingservice.port }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
