apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.webhook: ""
    notifications.argoproj.io/subscribe.on-sync-failed.webhook: ""
spec:
  project: default
  source:
    repoURL: https://github.com/Shorya86/gitops-cicd-online-boutique.git
    targetRevision: main
    path: helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
